version: "3"
services:
  app:
    container_name: downwrite-api
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    command: npm start
  mongo:
    container_name: downwrite-db
    image: mongo:latest
    ports:
      - "27017:27017"
