version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: npm start
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
